services:
  vkr-backend:
    container_name: vkr-backend
    build: docker/images/php
    working_dir: /app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
      - .composer:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=${APP_ENV}
      - ML_SERVICE_BASE_URL=${ML_SERVICE_BASE_URL:-http://vkr-ml-api:8000}
    env_file:
      - .env
      - .env.local
    networks:
      - vkr-inner-network
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G


networks:
  vkr-inner-network:
    name: vkr-scinside-internal
    external: true
